# Generated by Django 4.2.5 on 2023-11-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='frequency',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
