[tool.ruff]
line-length = 125
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "UP",  # pyupgrade
]

exclude = [
    "settings.py",
    "migrations",
    ".git",
    ".ruff_cache",
    "venv",
    "pycache",
]

[tool.ruff.pydocstyle]
convention = "google"