# Generated by Django 4.2.5 on 2023-09-25 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0002_timestampedmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeStampedModel',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
