# Generated by Django 4.2.5 on 2023-10-24 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0008_alter_company_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='company.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InvitationAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.action')),
                ('status', models.CharField(choices=[('MEMBER', 'MEMBER'), ('OWNER', 'OWNER')])),
            ],
            options={
                'abstract': False,
            },
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='RequestAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.action')),
                ('status', models.CharField(choices=[('MEMBER', 'MEMBER'), ('OWNER', 'OWNER')])),
            ],
            options={
                'abstract': False,
            },
            bases=('actions.action',),
        ),
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='actions.action')),
                ('status', models.CharField(choices=[('MEMBER', 'MEMBER'), ('OWNER', 'OWNER')])),
            ],
            options={
                'abstract': False,
            },
            bases=('actions.action',),
        ),
    ]
