# Generated by Django 4.2.5 on 2023-10-31 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitationaction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('revoked', 'REVOKED'), ('declined', 'DECLINED'), ('approved', 'APPROVED')]),
        ),
        migrations.AlterField(
            model_name='requestaction',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('canceled', 'CANCELED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED')]),
        ),
    ]
