# Generated by Django 4.2.5 on 2023-10-17 19:48

import actions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='status',
            field=models.CharField(choices=[(actions.models.InvitationStatus['invited'], 'Invited'), (actions.models.InvitationStatus['revoke'], 'Revoked'), (actions.models.InvitationStatus['requested'], 'Requested'), (actions.models.InvitationStatus['rejected'], 'Rejected'), (actions.models.InvitationStatus['declined'], 'Declined'), (actions.models.InvitationStatus['member'], 'Member'), (actions.models.InvitationStatus['owner'], 'Owner')], max_length=20),
        ),
    ]
