# Generated by Django 4.2.5 on 2023-10-18 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_rename_company_id_actions_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actions',
            old_name='status_id',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='actions',
            old_name='user_id',
            new_name='user',
        ),
    ]
