# Generated by Django 4.2.5 on 2023-10-20 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_company_name'),
        ('actions', '0004_rename_status_id_actions_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='company',
            field=models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='company.company'),
        ),
        migrations.AlterField(
            model_name='actions',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
