# Generated by Django 4.2.5 on 2023-10-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.AddField(
            model_name='company',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
    ]
