# Generated by Django 4.2.5 on 2023-10-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_company_members'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompanyInvitation',
        ),
    ]
