# Generated by Django 4.2.5 on 2023-10-18 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_delete_companyinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='members',
        ),
        migrations.RemoveField(
            model_name='company',
            name='owner',
        ),
    ]
