name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_HOST: db
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 12345
          POSTGRES_NAME: postgres
        ports:
          - 5432:5432

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        env:
          DJANGO_SETTINGS_MODULE: quizes.settings
          DATABASE_URL: postgres://admin:12345@localhost:5432/postgres

      - name: Remove postmaster.pid
        run: |
          cd ..
          ls -a
          echo 'hello'
          cd ..
          ls -a

#      - name: Set up test database
#        run: |
#          python manage.py migrate
#          python manage.py createcachetable

