name: Django Tests and Code Quality

on:
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Set up Docker Buildx
        run: |
          docker buildx create --use
          docker buildx inspect default --bootstrap

      - name: Build Docker image
        run: docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --iidfile /tmp/docker-build-push-N1BT0A/iidfile --tag backend --load --metadata-file /tmp/docker-build-push-N1BT0A/metadata-file .

      - name: Run Ruff lint
        run: docker-compose run --rm app sh -c "ruff check ."

      - name: Run Django tests
        run: docker-compose run --rm app sh -c "python manage.py test"