name: Django Tests and Code Quality

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      REDIS_NAME: ${{ secrets.REDIS_NAME }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Export secrets
        run: |
          echo "POSTGRES_NAME=${POSTGRES_NAME}" > .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "POSTGRES_HOST=${POSTGRES_HOST}" >> .env
          echo "REDIS_NAME=${REDIS_NAME}" >> .env
          echo "REDIS_PORT=${REDIS_PORT}" >> .env
          echo "EMAIL_HOST_USER=${EMAIL_HOST_USER}" >> .env
          echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" >> .env

      - name: Run Ruff lint
        run: docker-compose run --rm app sh -c "ruff check ."

      - name: Run Django tests
        run: docker-compose run --rm app sh -c "python manage.py test"