name: Django Tests and Code Quality

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_NAME: ${{ secrets.POSTGRES_NAME }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      REDIS_NAME: ${{ secrets.REDIS_NAME }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      EMAIL_HOST_PASSWORD: ${{ secrets.EMAIL_HOST_PASSWORD }}
      REDIS_PORT: ${{ secrets.REDIS_PORT }}
      EMAIL_HOST_USER: ${{ secrets.EMAIL_HOST_USER }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Export secrets
        run: |
          echo "POSTGRES_NAME=${POSTGRES_NAME}" >> .env
          echo "POSTGRES_USER=${POSTGRES_USER}" >> .env
          echo "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}" >> .env
          echo "POSTGRES_HOST=${POSTGRES_HOST}" >> .env
          echo "REDIS_NAME=${REDIS_NAME}" >> .env
          echo "REDIS_PORT=${REDIS_PORT}" >> .env
          echo "EMAIL_HOST_USER=${EMAIL_HOST_USER}" >> .env
          echo "EMAIL_HOST_PASSWORD=${EMAIL_HOST_PASSWORD}" >> .env

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run linter
        run: ruff check .

      - name: Run Django tests
        run: python manage.py test
