name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 12345
        ports:
          - 5433:5432

      redis:
        image: redis:latest
        ports:
          - 6379:6379

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        env:
          DJANGO_SETTINGS_MODULE: quizes.settings

      - name: Set up test database
        run: |
          python manage.py migrate
          python manage.py createcachetable
        env:
          DATABASE_URL: postgres://admin:12345@db:5432/postgres

      - name: Run Tests
        run: python manage.py test
