name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: |
          echo "POSTGRES_NAME=postgres" >> .env
          echo "POSTGRES_USER=admin" >> .env
          echo "POSTGRES_PASSWORD=12345" >> .env
          echo "POSTGRES_HOST=db" >> .env
          echo "REDIS_NAME=redis" >> .env
          echo "REDIS_PORT=6379" >> .env
          echo "EMAIL_HOST_USER=quizzesproj@gmail.com" >> .env
          echo "EMAIL_HOST_PASSWORD=ksrhezkjpjrrrmoa" >> .env

      - name: Set up Docker Compose
        run: |
          docker-compose --version
        continue-on-error: true

      - name: Build and start services
        run: |
          docker-compose up -d

      - name: Run database migrations
        run: |
          docker exec meduzzen_backend_internship_app_1 python manage.py migrate

      - name: Run linter
        run: |
          docker exec meduzzen_backend_internship_app_1 ruff check .

      - name: Run tests
        run: |
          docker exec meduzzen_backend_internship_app_1 python manage.py test
      
          
  

