name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13.3
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: 12345
        ports:
          - 5433:5432

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
        env:
          DATABASE_URL: postgres://admin:12345@localhost:5433/postgres
          DJANGO_SECRET_KEY: 'your-secret-key'

      - name: Start Docker Compose
        run: docker-compose up -d
        working-directory: ./path-to-docker-compose-directory

      - name: Run Tests
        run: python manage.py test
        env:
          DJANGO_SETTINGS_MODULE: your_project_name.settings

      - name: Stop Docker Compose
        run: docker-compose down
        working-directory: ./path-to-docker-compose-directory
