name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          docker-compose --version
        continue-on-error: true

      - name: Build and start services
        run: |
          docker-compose up -d
      
      - name: Show containers
        run: |
          docker ps -a

      - name: Run database migrations
        run: |
          docker exec -it meduzzen_backend_internship_app_1 python manage.py migrate
  

