name: Django Tests and PostgreSQL

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      POSTGRES_PASSWORD: mysecretpassword
      DJANGO_SETTINGS_MODULE: quizes.settings

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Start PostgreSQL
        run: |
          docker run --name postgres -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d -p 5432:5432 postgres:13.3

      - name: Wait for PostgreSQL to start
        run: |
          sleep 10  # Зачекайте 10 секунд

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        run: |
          python manage.py test

      - name: Stop PostgreSQL
        run: |
          docker stop postgres
          docker rm postgres
